TRUNCATE TABLE [api_owner].[LogCommand]
TRUNCATE TABLE [fix_owner].[LogCommand]
TRUNCATE TABLE [fix_owner].[LogProcesos]
TRUNCATE TABLE [fix_owner].[LogSeguridad]
TRUNCATE TABLE [fix_owner].[LogSqlErrores]
TRUNCATE TABLE [fix_owner].[LogToOrderRouter]

TRUNCATE TABLE [fix_owner].[MensajesEnviadosMarketData]
TRUNCATE TABLE [fix_owner].[MensajesEnviadosOrdenes]
TRUNCATE TABLE [fix_owner].[MensajesRecibidosMarketData]
TRUNCATE TABLE [fix_owner].[MensajesRecibidosOrdenes]


TRUNCATE TABLE [orden_owner].[LogBitacoraOrdenes]
TRUNCATE TABLE [orden_owner].[LogCommand]
TRUNCATE TABLE [orden_owner].[LogProcesos]
TRUNCATE TABLE [orden_owner].[LogSeguridad]
TRUNCATE TABLE [orden_owner].[LogSqlErrores]


TRUNCATE TABLE [fix_owner].[OrdenesRelacionIds]
TRUNCATE TABLE [orden_owner].[DailyHistoricalPrice]
TRUNCATE TABLE [orden_owner].[Ofertas]
DELETE FROM [orden_owner].[OrdenesHistorico]
TRUNCATE TABLE [orden_owner].[OrdenOperacionHistorico]
TRUNCATE TABLE [orden_owner].[OrdenOperacion]
DELETE FROM [orden_owner].[Ordenes]
TRUNCATE TABLE [orden_owner].[PortfolioUsuario]
TRUNCATE TABLE [orden_owner].[PortfoliosComposicion]
DELETE FROM [orden_owner].[Portfolios]
TRUNCATE TABLE [orden_owner].[PreciosHistoricos]
TRUNCATE TABLE [orden_owner].[Precios]
TRUNCATE TABLE [orden_owner].[Saldos]
TRUNCATE TABLE [shared_owner].[HistoricoPassword]
TRUNCATE TABLE [shared_owner].[LogAuditoria]
TRUNCATE TABLE [shared_owner].[Sesiones]
TRUNCATE TABLE [shared_owner].[EstadoSistema]
--VER DE INSERTAR LUEGO
TRUNCATE TABLE [orden_owner].[ProductosPorMercados]
DELETE FROM [orden_owner].[Productos]
DELETE [shared_owner].[RuedasBySecurityList]
DELETE [shared_owner].[SecurityList]
TRUNCATE TABLE [fix_owner].[ConfiguracionInterfaces]
DELETE FROM [shared_owner].[Mercados]
DELETE FROM [shared_owner].[RolUsuario]
DELETE FROM [shared_owner].[CustomizacionUsuario]
DELETE FROM [shared_owner].[Usuarios]
DELETE FROM [shared_owner].[PartiesHierarchy]
DELETE FROM [shared_owner].[Parties]

