CREATE TABLE [orden_owner].[OperacionHistorico] (
    [IdOperacionHistorico]		INT  CONSTRAINT [DF_OperacionHistorico_IdOperacionHistorico] DEFAULT (NEXT VALUE FOR [orden_owner].[SQ_OperacionHistorico]) NOT NULL,
	[FechaLiquidacion]			DATETIME	NULL,
	[Rueda]						VARCHAR(10)	NOT NULL,
	[TradeReportID]				VARCHAR(30)	NOT NULL,
	--[IdTipoNegociacion]			TINYINT	NOT NULL,
	[IdProducto]				INT	NOT NULL,
	[IdPlazo]					TINYINT	NULL,
	[IdMoneda]					TINYINT	NULL,
	[PrecioTasa]				DECIMAL (20, 10)	NOT NULL,
    [Cantidad]                  DECIMAL (18, 4)     NOT NULL,
	[IdMercado]					TINYINT	NOT NULL,
	[EsAlta]					BIT					 CONSTRAINT [DF__OperacionHistorico__EsAlta] DEFAULT ((0)) NOT NULL,
    [OperaPorTasa]				BIT					 CONSTRAINT [DF__OperacionHistorico__OperaPorTasa] DEFAULT ((0)) NOT NULL,
	[Fecha]						DATETIME	NOT NULL,
	[ProductoNombreLargo]		VARCHAR(80)	NOT NULL,
	[LastSpotRate]				DECIMAL(18,8) NOT NULL,
	[ReferencePrice]			DECIMAL(18,8) NULL,
	[Valorizacion]				DECIMAL(24,8) NULL,
	[PartyComprador]			VARCHAR(30)	NOT NULL,
	[PartyVendedor]				VARCHAR(30)	NOT NULL,
	[MensajeTextoPlano]			VARCHAR(MAX),
    CONSTRAINT [PK_OperacionHistorico] PRIMARY KEY CLUSTERED ([IdOperacionHistorico] ASC),
	CONSTRAINT [FK_OperacionHistorico_Productos] FOREIGN KEY([IdProducto]) REFERENCES [orden_owner].[Productos] ([IdProducto]),
	--CONSTRAINT [FK_OperacionHistorico_TipoNegociacion] FOREIGN KEY([IdTipoNegociacion]) REFERENCES [fix_owner].[TipoNegociacion] ([IdTipoNegociacion]),
	CONSTRAINT [FK_OperacionHistorico_Plazo] FOREIGN KEY([IdPlazo]) REFERENCES [orden_owner].[Plazos] ([IdPlazo]),
	CONSTRAINT [FK_OperacionHistorico_Moneda] FOREIGN KEY([IdMoneda]) REFERENCES [shared_owner].[Monedas] ([IdMoneda]),
	CONSTRAINT [FK_OperacionHistorico_Mercado] FOREIGN KEY([IdMercado]) REFERENCES [shared_owner].[Mercados] ([IdMercado])
);

