CREATE TABLE [orden_owner].[OrdenesHistorico] (
    [IdOrdenHistorico]   INT              NOT NULL,
    [CompraVenta]        VARCHAR (1)      NOT NULL,
    [IdProducto]         INT              NOT NULL,
    [IdMoneda]           TINYINT          NOT NULL,
    [IdMercado]          TINYINT          NULL,
    [IdPersona]          INT              NULL,
	[IdUsuario]          INT              NULL,
	[IdEnNombreDe]       INT              NULL,
    [FechaConcertacion]  DATETIME         NOT NULL,
    [Cantidad]           DECIMAL (18, 4)  NOT NULL,
    [PrecioLimite]       DECIMAL (20, 10) NULL,
    [IdEstado]           TINYINT          NOT NULL,
    [IdMotivoBaja]       TINYINT          NULL,
    [NumeroOrdenInterno] INT              NOT NULL,
    [IdTipoVigencia]     TINYINT          NULL,
    [FechaVencimiento]   DATETIME         NULL,
    [NumeroOrdenMercado] VARCHAR (100)    NULL,
	[Plazo]				 TINYINT		  NULL, 
    [IdTipoOrden]		 TINYINT		  NOT NULL, 
    [Timestamp]			 TIMESTAMP		  NOT NULL, 
    [IdSourceApplication]TINYINT		  NULL, 
	[IdOrdenHistoricoDeReferencia]INT              NULL,
	[EquivalentRate]			  DECIMAL(18,8)	   NULL,
    [OperoPorTasa]				BIT                 NOT NULL CONSTRAINT [DF_OrdenesHistorico_OperoPorTasa]  DEFAULT ((0)),
	[PrecioVinculado]			DECIMAL(20,10)	    NULL,
    CONSTRAINT [PK_OrdenesHistorico] PRIMARY KEY CLUSTERED ([IdOrdenHistorico] ASC),
    CONSTRAINT [FK_OrdenesHistorico_EstadosOrden] FOREIGN KEY ([IdEstado]) REFERENCES [orden_owner].[EstadosOrden] ([IdEstadoOrden]),
    CONSTRAINT [FK_OrdenesHistorico_Mercados] FOREIGN KEY ([IdMercado]) REFERENCES [shared_owner].[Mercados] ([IdMercado]),
    CONSTRAINT [FK_OrdenesHistorico_Monedas] FOREIGN KEY ([IdMoneda]) REFERENCES [shared_owner].[Monedas] ([IdMoneda]),
    CONSTRAINT [FK_OrdenesHistorico_Parties] FOREIGN KEY ([IdPersona]) REFERENCES [shared_owner].[Parties] ([IdParty]),
	CONSTRAINT [FK_OrdenesHistorico_Usuarios] FOREIGN KEY ([IdUsuario]) REFERENCES [shared_owner].[Usuarios] ([IdUsuario]),
    CONSTRAINT [FK_OrdenesHistorico_Productos] FOREIGN KEY ([IdProducto]) REFERENCES [orden_owner].[Productos] ([IdProducto]),
    CONSTRAINT [FK_OrdenesHistorico_TiposVigencia] FOREIGN KEY ([IdTipoVigencia]) REFERENCES [shared_owner].[TiposVigencia] ([IdTipoVigencia]),
	CONSTRAINT [FK_OrdenesHistorico_TiposOrden] FOREIGN KEY([IdTipoOrden]) REFERENCES [orden_owner].[TiposOrden] ([IdTipoOrden]),
	CONSTRAINT [FK_OrdenesHistorico_Plazo] FOREIGN KEY([Plazo]) REFERENCES [orden_owner].[Plazos] ([IdPlazo]),
	--CONSTRAINT [FK_OrdenesHistorico_SourceApplication] FOREIGN KEY([IdSourceApplication]) REFERENCES [orden_owner].[SourcesApplication] ([IdSourceApplication]),
	CONSTRAINT [FK_OrdenesHistorico_IdOrdenHistoricoDeReferencia] FOREIGN KEY([IdOrdenHistoricoDeReferencia]) REFERENCES [orden_owner].[OrdenesHistorico] ([IdOrdenHistorico])
);



