CREATE TABLE [orden_owner].[Ordenes] (
    [IdOrden]                     INT              CONSTRAINT [DF_Ordenes_IdOrden] DEFAULT (NEXT VALUE FOR [orden_owner].[SQ_Ordenes]) NOT NULL,
    [CompraVenta]                 VARCHAR (1)      NOT NULL,
    [IdProducto]                  INT              NOT NULL,
    [IdMoneda]                    TINYINT          NOT NULL,
    [IdMercado]                   TINYINT          NULL,
	[IdPersona]                   INT              NOT NULL,
	[IdUsuario]                   INT              NULL,
	[IdEnNombreDe]                INT              NULL,
    [FechaConcertacion]           DATETIME         NOT NULL,
    [Cantidad]                    DECIMAL (18, 4)  NOT NULL,
	[CantidadMinima]              DECIMAL (18, 4)  NULL,
    [PrecioLimite]                DECIMAL (20, 10) NULL,
    [IdEstado]					  TINYINT          NOT NULL,
    [IdMotivoBaja]                TINYINT          NULL,
    [NumeroOrdenInterno]          INT              DEFAULT (NEXT VALUE FOR [orden_owner].[SQ_Ordenes_NumeroOrdenInterno]) NOT NULL,
    [IdTipoVigencia]              TINYINT          NULL,
    [FechaVencimiento]            DATETIME         NULL,
    [NumeroOrdenMercado]          VARCHAR (100)    NULL,
    [Plazo]						  TINYINT		   NULL, 
    [IdTipoOrden]				  TINYINT		   NOT NULL, 
    [Timestamp]					  TIMESTAMP		   NOT NULL, 
    [IdSourceApplication]		  TINYINT		   NULL, 
	[IdOrdenDeReferencia]		  INT              NULL,
	[EquivalentRate]			  DECIMAL(18,8)	   NULL,
    [OperoPorTasa]				BIT                 NOT NULL CONSTRAINT [DF_Ordenes_OperoPorTasa]  DEFAULT ((0)),
	[PrecioVinculado]			DECIMAL(20,10)	    NULL,
	[VisibleSiCancelada]		BIT                 NOT NULL CONSTRAINT [DF_Ordenes_VisibleSiCancelada]  DEFAULT ((1)),
    [Tasa] DECIMAL(20, 10) NULL, 
    [Valorizacion] DECIMAL(24, 8) NULL,
	[SettlementDate]     DATETIME        NULL,
    CONSTRAINT [PK_Ordenes] PRIMARY KEY CLUSTERED ([IdOrden] ASC),
    CONSTRAINT [FK_Ordenes_Productos] FOREIGN KEY([IdProducto]) REFERENCES [orden_owner].[Productos] ([IdProducto]),
	CONSTRAINT [FK_Ordenes_Parties] FOREIGN KEY ([IdPersona]) REFERENCES [shared_owner].[Parties] ([IdParty]),
	CONSTRAINT [FK_Ordenes_MotivosBaja] FOREIGN KEY([IdMotivoBaja]) REFERENCES [shared_owner].[MotivosBaja] ([IdMotivoBaja]),
	CONSTRAINT [FK_Ordenes_TiposVigencia] FOREIGN KEY([IdTipoVigencia]) REFERENCES [shared_owner].[TiposVigencia] ([IdTipoVigencia]),
	CONSTRAINT [FK_Ordenes_EstadosOrden] FOREIGN KEY([IdEstado]) REFERENCES [orden_owner].[EstadosOrden] ([IdEstadoOrden]),
	CONSTRAINT [FK_Ordenes_Mercado] FOREIGN KEY([IdMercado]) REFERENCES [shared_owner].[Mercados] ([IdMercado]),
	CONSTRAINT [FK_Ordenes_Moneda] FOREIGN KEY([IdMoneda]) REFERENCES [shared_owner].[Monedas] ([IdMoneda]),
	CONSTRAINT [FK_Ordenes_TiposOrden] FOREIGN KEY([IdTipoOrden]) REFERENCES [orden_owner].[TiposOrden] ([IdTipoOrden]),
	CONSTRAINT [FK_Ordenes_Plazo] FOREIGN KEY([Plazo]) REFERENCES [orden_owner].[Plazos] ([IdPlazo]),
	--CONSTRAINT [FK_Ordenes_SourceApplication] FOREIGN KEY([IdSourceApplication]) REFERENCES [orden_owner].[SourcesApplication] ([IdSourceApplication]),
	CONSTRAINT [FK_Ordenes_IdOrdenDeReferencia] FOREIGN KEY([IdOrdenDeReferencia]) REFERENCES [orden_owner].[Ordenes] ([IdOrden])
);

